version: '3.8'
services:
  mysql:
    image: library/mysql:8.0
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leboncode
    volumes:
      - $PWD/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - admin-leboncode:/var/lib/mysql
volumes:
  admin-leboncode:
